"""empty message

Revision ID: 42bbb1cb7814
Revises: 
Create Date: 2021-06-17 10:10:43.373573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42bbb1cb7814'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('con_user_course')
    # op.drop_table('tbl_student_course')
    # op.drop_table('tbl_course')
    # op.drop_table('tbl_user')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user',
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('surname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.ENUM('teacher', 'student'), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_of_update', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_course',
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_mark', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_of_update', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_student_course',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('mark', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_of_update', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(`active` in (0,1))', name='tbl_student_course_chk_2'),
    sa.CheckConstraint('(`complete` in (0,1))', name='tbl_student_course_chk_1'),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_course.id'], name='tbl_student_course_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_user.id'], name='tbl_student_course_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('con_user_course',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_course.id'], name='con_user_course_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], name='con_user_course_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
